#!/usr/bin/env python3
"""Record a launch instead of starting anything: {"launch": [argv…]}."""
import json
import os
import sys

args = [a for a in sys.argv[1:] if a != '-f']
with open(os.environ['FAKE_LOG'], 'a') as f:
    f.write(json.dumps({'launch': args}) + '\n')
